### ISSUE TITLE
BUG: Unable to open mission menu

### ISSUE THREAD

**Issue by trazodana** [titanlabs-mc/battle-pass#610]
### Describe the bug

Cannot open the mission menu, gives error when clicking

log: 

[17:28:53 ERROR]: Could not pass event InventoryClickEvent to BattlePass v4.7.3
java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "<local14>" is null
        at BattlePass-4.7.3.jar/io.github.battlepass.menus.menus.QuestOverviewMenu.pageableItem(QuestOverviewMenu.java:97) ~[BattlePass-4.7.3.jar:?]
        at BattlePass-4.7.3.jar/io.github.battlepass.menus.menus.QuestOverviewMenu.pageableItem(QuestOverviewMenu.java:31) ~[BattlePass-4.7.3.jar:?]
        at BattlePass-4.7.3.jar/me.hyfe.simplespigot.menu.PageableMenu.drawPageableItems(PageableMenu.java:65) ~[BattlePass-4.7.3.jar:?]
        at BattlePass-4.7.3.jar/io.github.battlepass.menus.menus.QuestOverviewMenu.redraw(QuestOverviewMenu.java:66) ~[BattlePass-4.7.3.jar:?]
        at BattlePass-4.7.3.jar/me.hyfe.simplespigot.menu.Menu.show(Menu.java:63) ~[BattlePass-4.7.3.jar:?]
        at BattlePass-4.7.3.jar/io.github.battlepass.actions.MenuAction.runAction(MenuAction.java:48) ~[BattlePass-4.7.3.jar:?]
        at BattlePass-4.7.3.jar/io.github.battlepass.actions.MenuAction.lambda$accept$1(MenuAction.java:22) ~[BattlePass-4.7.3.jar:?]
        at BattlePass-4.7.3.jar/io.github.battlepass.actions.MenuAction.checkCondition(MenuAction.java:63) ~[BattlePass-4.7.3.jar:?]
        at BattlePass-4.7.3.jar/io.github.battlepass.actions.MenuAction.accept(MenuAction.java:21) ~[BattlePass-4.7.3.jar:?]
        at BattlePass-4.7.3.jar/io.github.battlepass.menus.service.MenuIllustrator.runAction(MenuIllustrator.java:101) ~[BattlePass-4.7.3.jar:?]
        at BattlePass-4.7.3.jar/io.github.battlepass.menus.service.MenuIllustrator.lambda$draw$2(MenuIllustrator.java:90) ~[BattlePass-4.7.3.jar:?]
        at BattlePass-4.7.3.jar/me.hyfe.simplespigot.menu.listener.MenuListener.onInventoryClick(MenuListener.java:38) ~[BattlePass-4.7.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor859.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2321-2eaea6a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3306) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1632) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1342) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]

### How to reproduce

Type /pass

Click on the missions menu

### Server Log

https://mcpaste.io/6dc1b0cbdb93fe5d

**Comment by KPGTB** [comment]
Hey! Can you send me your configuration of quest-overview menu? (`plugins/BattlePass/menus/quest-overview.yml`)

**Comment by KPGTB** [comment]
Anyway, I found what causes that issue. Fix will be available in the next update

**Comment by trazodana** [comment]
[03:10:13 ERROR]: Could not pass event InventoryClickEvent to BattlePass v4.7.5
java.lang.NullPointerException: Cannot invoke "java.util.List.add(Object)" because "<local14>" is null
        at BattlePass-4.7.5.jar/io.github.battlepass.menus.menus.QuestOverviewMenu.pageableItem(QuestOverviewMenu.java:97) ~[BattlePass-4.7.5.jar:?]
        at BattlePass-4.7.5.jar/io.github.battlepass.menus.menus.QuestOverviewMenu.pageableItem(QuestOverviewMenu.java:31) ~[BattlePass-4.7.5.jar:?]
        at BattlePass-4.7.5.jar/me.hyfe.simplespigot.menu.PageableMenu.drawPageableItems(PageableMenu.java:65) ~[BattlePass-4.7.5.jar:?]
        at BattlePass-4.7.5.jar/io.github.battlepass.menus.menus.QuestOverviewMenu.redraw(QuestOverviewMenu.java:66) ~[BattlePass-4.7.5.jar:?]
        at BattlePass-4.7.5.jar/me.hyfe.simplespigot.menu.Menu.show(Menu.java:63) ~[BattlePass-4.7.5.jar:?]
        at BattlePass-4.7.5.jar/io.github.battlepass.actions.MenuAction.runAction(MenuAction.java:48) ~[BattlePass-4.7.5.jar:?]
        at BattlePass-4.7.5.jar/io.github.battlepass.actions.MenuAction.lambda$accept$1(MenuAction.java:22) ~[BattlePass-4.7.5.jar:?]
        at BattlePass-4.7.5.jar/io.github.battlepass.actions.MenuAction.checkCondition(MenuAction.java:63) ~[BattlePass-4.7.5.jar:?]
        at BattlePass-4.7.5.jar/io.github.battlepass.actions.MenuAction.accept(MenuAction.java:21) ~[BattlePass-4.7.5.jar:?]
        at BattlePass-4.7.5.jar/io.github.battlepass.menus.service.MenuIllustrator.runAction(MenuIllustrator.java:101) ~[BattlePass-4.7.5.jar:?]
        at BattlePass-4.7.5.jar/io.github.battlepass.menus.service.MenuIllustrator.lambda$draw$2(MenuIllustrator.java:90) ~[BattlePass-4.7.5.jar:?]
        at BattlePass-4.7.5.jar/me.hyfe.simplespigot.menu.listener.MenuListener.onInventoryClick(MenuListener.java:38) ~[BattlePass-4.7.5.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor1185.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:1.21.1-2321-2eaea6a]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:131) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:630) ~[paper-mojangapi-1.21.1-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleContainerClick(ServerGamePacketListenerImpl.java:3306) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:69) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.handle(ServerboundContainerClickPacket.java:33) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$0(PacketUtils.java:56) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:151) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1581) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:201) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:125) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1558) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1551) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:135) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.MinecraftServer.managedBlock(MinecraftServer.java:1510) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1517) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1362) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:333) ~[purpur-1.21.1.jar:1.21.1-2321-2eaea6a]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
        
        
        I saw that you marked it as fixed, but if the solution was in the latest 4.7.5 update, then the problem continues

**Comment by KPGTB** [comment]
I'm sorry, but you need to wait. This issue will be automatically closed when GC merge this fix.
